spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/transportador?createDatabaseIfNotExist=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
